WITH M AS (
  SELECT 
    H.MARKET,
    CURRENT_DATE AS DATE_KPI, 
    H.SELLER_ID, 
    H.SELLER_NAME, 
    H.SELLER_OWNER_NAME,
    S.SELLER_TIERING,
    S.TYPE_OF_ACTIVITY
  FROM manual-queries-prod-230608.legacy_tables.historic_quality_order_management AS H
  LEFT JOIN universe-prod-20220914.supply.universe_sellers_and_prospects_markets AS S 
    ON S.SELLER_ID = H.SELLER_ID AND H.MARKET = S.MARKET
  WHERE H.MARKET = 'JP'
  AND H.DATE_KPI BETWEEN DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY) AND CURRENT_DATE
  GROUP BY 1,2,3,4,5,6,7
),

D30 AS (
  SELECT
    CURRENT_DATE AS DATE_KPI,
    MARKET, 
    SELLER_ID, 
    SUM(NB_DEFECTIVE_ISSUE) AS NB_DEFECTIVE_30D,
    SUM(NB_ORDERLINE_DELIVERED_30D) AS NB_ORDERLINE_DELIVERED_30D, 
    ROUND(SUM(NB_DEFECTIVE_ISSUE)/NULLIF(SUM(NB_ORDERLINE_DELIVERED_30D),0),6) AS DEFECTIVE_RATE_30D
  FROM manual-queries-prod-230608.legacy_tables.historic_quality_order_management
  WHERE MARKET = 'JP'
  AND DATE_KPI BETWEEN DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY) AND CURRENT_DATE
  GROUP BY 1,2,3
),

A AS (
  SELECT 
    CURRENT_DATE AS DATE_KPI, 
    MARKET,
    SELLER_ID, 
    SUM(NB_APPEARANCE_ISSUE) AS NB_APPEARANCE_ISSUE,
    SUM(NB_ORDERLINE_DELIVERED_30D) AS NB_ORDERLINE_DELIVERED_30D, 
    ROUND(SUM(NB_APPEARANCE_ISSUE)/NULLIF(SUM(NB_ORDERLINE_DELIVERED_30D),0),6) AS APPEARANCE_ISSUE_30D
  FROM manual-queries-prod-230608.legacy_tables.historic_quality_order_management
  WHERE MARKET = 'JP'
  AND DATE_KPI BETWEEN DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY) AND CURRENT_DATE 
  GROUP BY 1,2,3
)

SELECT 
  M.DATE_KPI,
  CONCAT(DATE_SUB(M.DATE_KPI, INTERVAL 30 DAY), ' to ', M.DATE_KPI) AS TIME_PERIOD,
  -- Keep original ID for joining but display the clean version
  CASE 
    WHEN RIGHT(TRIM(M.SELLER_ID), 2) = 'AP' THEN LEFT(TRIM(M.SELLER_ID), LENGTH(TRIM(M.SELLER_ID)) - 2)
    ELSE TRIM(M.SELLER_ID)
  END AS SELLER_ID, 
  M.SELLER_NAME,
  D30.DEFECTIVE_RATE_30D,
  CASE 
    WHEN D30.DEFECTIVE_RATE_30D > 0.04 AND D30.NB_DEFECTIVE_30D >= 2 THEN 'Critical' 
    WHEN D30.DEFECTIVE_RATE_30D > 0.03 AND D30.NB_DEFECTIVE_30D >= 2 THEN 'Alerting'
    ELSE '' 
  END AS DEFECTIVE_30D_LABEL,
  A.APPEARANCE_ISSUE_30D,
  CASE 
    WHEN A.APPEARANCE_ISSUE_30D > 0.01 AND A.NB_APPEARANCE_ISSUE >= 2 THEN 'Critical' 
    WHEN A.APPEARANCE_ISSUE_30D > 0.0075 AND A.NB_APPEARANCE_ISSUE >= 2 THEN 'Alerting'
    ELSE '' 
  END AS APPEARANCE_ISSUE_LABEL,
  C.EMAIL
FROM M
LEFT JOIN D30 ON M.DATE_KPI = D30.DATE_KPI AND M.SELLER_ID = D30.SELLER_ID AND M.MARKET = D30.MARKET
LEFT JOIN A ON M.DATE_KPI = A.DATE_KPI AND M.SELLER_ID = A.SELLER_ID AND M.MARKET = A.MARKET
LEFT JOIN `data-champions-prod-230414.jp_data.jp_sellers_contact` C ON TRIM(M.SELLER_ID) = TRIM(C.SELLER_ID)
WHERE (
  (D30.DEFECTIVE_RATE_30D > 0.03 AND D30.NB_DEFECTIVE_30D >= 2) OR
  (A.APPEARANCE_ISSUE_30D > 0.0075 AND A.NB_APPEARANCE_ISSUE >= 2)
)
ORDER BY D30.DEFECTIVE_RATE_30D DESC, A.APPEARANCE_ISSUE_30D DESC